export interface FormFieldLabels {
  title: string;
  labels: Record<string, string>;
}

export const fieldLabels: Record<string, FormFieldLabels> = {
  "w-9": {
    title: "IRS Form W-9",
    labels: {
      "topmostSubform[0].Page1[0].f1_01[0]": "Name (as shown on your income tax return)",
      "topmostSubform[0].Page1[0].f1_02[0]": "Business name / Disregarded entity name, if different from above",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].c1_1[0]": "Individual / sole proprietor",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].c1_1[1]": "C corporation",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].c1_1[2]": "S corporation",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].c1_1[3]": "Partnership",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].c1_1[4]": "Trust / estate",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].c1_1[5]": "Limited liability company (LLC)",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].f1_03[0]": "LLC tax classification",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].c1_1[6]": "Other (see instructions)",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].f1_04[0]": "Other tax classification",
      "topmostSubform[0].Page1[0].Boxes3a-b_ReadOrder[0].c1_2[0]": "Exempt from backup withholding",
      "topmostSubform[0].Page1[0].f1_05[0]": "Exempt payee code (if any)",
      "topmostSubform[0].Page1[0].f1_06[0]": "Exemption from FATCA reporting code (if any)",
      "topmostSubform[0].Page1[0].Address_ReadOrder[0].f1_07[0]": "Address (number, street, and apt. or suite no.)",
      "topmostSubform[0].Page1[0].Address_ReadOrder[0].f1_08[0]": "City, state, and ZIP code",
      "topmostSubform[0].Page1[0].f1_09[0]": "Requester's name and address (optional)",
      "topmostSubform[0].Page1[0].f1_10[0]": "List account number(s) here (optional)",
      "topmostSubform[0].Page1[0].f1_11[0]": "Social security number (first 3 digits)",
      "topmostSubform[0].Page1[0].f1_12[0]": "Social security number (middle 2 digits)",
      "topmostSubform[0].Page1[0].f1_13[0]": "Social security number (last 4 digits)",
      "topmostSubform[0].Page1[0].f1_14[0]": "Employer identification number (first 2 digits)",
      "topmostSubform[0].Page1[0].f1_15[0]": "Employer identification number (last 7 digits)",
    },
  },
  "w-4": {
    title: "IRS Form W-4",
    labels: {
      "topmostSubform[0].Page1[0].Step1a[0].f1_01[0]": "First name and middle initial",
      "topmostSubform[0].Page1[0].Step1a[0].f1_02[0]": "Last name",
      "topmostSubform[0].Page1[0].Step1a[0].f1_03[0]": "Address",
      "topmostSubform[0].Page1[0].Step1a[0].f1_04[0]": "City/town, state, and ZIP",
      "topmostSubform[0].Page1[0].f1_05[0]": "Social security number",
      "topmostSubform[0].Page1[0].c1_1[0]": "Single or Married filing separately",
      "topmostSubform[0].Page1[0].c1_1[1]": "Married filing jointly or Qualifying surviving spouse",
      "topmostSubform[0].Page1[0].c1_1[2]": "Head of household",
      "topmostSubform[0].Page1[0].c1_2[0]": "I have two jobs or a working spouse (Step 2c)",
      "topmostSubform[0].Page1[0].Step3_ReadOrder[0].f1_06[0]": "Qualifying children under age 17 (Step 3)",
      "topmostSubform[0].Page1[0].Step3_ReadOrder[0].f1_07[0]": "Other dependents (Step 3)",
      "topmostSubform[0].Page1[0].f1_08[0]": "Other income (Step 4a)",
      "topmostSubform[0].Page1[0].f1_09[0]": "Deductions (Step 4b)",
      "topmostSubform[0].Page1[0].f1_10[0]": "Extra withholding (Step 4c)",
      "topmostSubform[0].Page1[0].c1_3[0]": "I have two jobs or a working spouse (Step 2c)",
      "topmostSubform[0].Page1[0].f1_12[0]": "Employee's signature",
      "topmostSubform[0].Page1[0].f1_13[0]": "Date",
      "topmostSubform[0].Page1[0].f1_14[0]": "Employer identification number (EIN)",
      "topmostSubform[0].Page3[0].f3_01[0]": "Multiple Jobs Worksheet — extra withholding",
      "topmostSubform[0].Page3[0].f3_02[0]": "Multiple Jobs Worksheet — Line 1",
      "topmostSubform[0].Page3[0].f3_03[0]": "Multiple Jobs Worksheet — Line 2a",
      "topmostSubform[0].Page3[0].f3_04[0]": "Multiple Jobs Worksheet — Line 2b",
      "topmostSubform[0].Page3[0].f3_05[0]": "Multiple Jobs Worksheet — Line 3",
      "topmostSubform[0].Page3[0].f3_06[0]": "Multiple Jobs Worksheet — Line 4",
      "topmostSubform[0].Page4[0].f4_01[0]": "Deductions Worksheet — Line 1a",
      "topmostSubform[0].Page4[0].f4_02[0]": "Deductions Worksheet — Line 1b",
      "topmostSubform[0].Page4[0].f4_03[0]": "Deductions Worksheet — Line 1c",
      "topmostSubform[0].Page4[0].f4_04[0]": "Deductions Worksheet — Line 1d",
      "topmostSubform[0].Page4[0].f4_05[0]": "Deductions Worksheet — Line 3a",
      "topmostSubform[0].Page4[0].f4_06[0]": "Deductions Worksheet — Line 3b",
      "topmostSubform[0].Page4[0].f4_07[0]": "Deductions Worksheet — Line 3c",
      "topmostSubform[0].Page4[0].f4_08[0]": "Deductions Worksheet — Line 4",
      "topmostSubform[0].Page4[0].f4_09[0]": "Deductions Worksheet — Line 6a",
      "topmostSubform[0].Page4[0].f4_10[0]": "Deductions Worksheet — Line 6b",
      "topmostSubform[0].Page4[0].f4_11[0]": "Deductions Worksheet — Line 6c",
      "topmostSubform[0].Page4[0].f4_12[0]": "Deductions Worksheet — Line 6d",
      "topmostSubform[0].Page4[0].f4_13[0]": "Deductions Worksheet — Line 6e",
      "topmostSubform[0].Page4[0].f4_14[0]": "Deductions Worksheet — Line 7",
      "topmostSubform[0].Page4[0].f4_15[0]": "Deductions Worksheet — Line 8a",
      "topmostSubform[0].Page4[0].f4_16[0]": "Deductions Worksheet — Line 8b",
      "topmostSubform[0].Page4[0].f4_17[0]": "Deductions Worksheet — Line 9",
      "topmostSubform[0].Page4[0].f4_18[0]": "Deductions Worksheet — Line 10",
      "topmostSubform[0].Page4[0].f4_19[0]": "Deductions Worksheet — Line 11",
      "topmostSubform[0].Page4[0].f4_20[0]": "Deductions Worksheet — Line 12",
      "topmostSubform[0].Page4[0].f4_21[0]": "Deductions Worksheet — Line 13",
      "topmostSubform[0].Page4[0].f4_22[0]": "Deductions Worksheet — Line 14",
      "topmostSubform[0].Page4[0].f4_23[0]": "Deductions Worksheet — Line 15",
    },
  },
  "ds-82": {
    title: "U.S. Department of State Form DS-82",
    labels: {
      lastName: "1. Last name",
      firstName: "1. First name",
      middleName: "1. Middle name",
      dateOfBirth: "2. Date of Birth (MM/DD/YYYY)",
      sex: "3. Sex (M/F)",
      placeOfBirth: "4. Place of Birth",
      ssn: "5. Social Security Number",
      email: "6. Email",
      phone: "7. Primary Contact Phone Number",
      mailingAddress1: "8. Mailing Address Line 1",
      mailingAddress2: "8. Mailing Address Line 2",
      city: "8. City",
      state: "8. State",
      zip: "8. Zip Code",
      country: "8. Country",
      previousNameA: "9. Other names used (A)",
      previousNameB: "9. Other names used (B)",
      passportName: "10. Name as printed on most recent passport",
      passportBookNumber: "10. Most recent passport book number",
      passportBookIssueDate: "10. Book issue date",
      passportCardNumber: "10. Most recent passport card number",
      passportCardIssueDate: "10. Card issue date",
      nameChangePlace: "11. Place of name change",
      nameChangeDate: "11. Date of name change",
      signatureDate: "Signature date",
      applicantName: "Name of Applicant",
      dateOfBirth2: "Date of Birth (Page 2)",
      height: "12. Height",
      hairColor: "13. Hair Color",
      eyeColor: "14. Eye Color",
      occupation: "15. Occupation",
      employer: "16. Employer or School",
      additionalPhone1: "17. Additional Phone 1",
      additionalPhone2: "17. Additional Phone 2",
      permanentAddress1: "18. Permanent Address Line 1",
      permanentApt: "18. Apartment/Unit",
      permanentCity: "18. City",
      permanentState: "18. State",
      permanentZip: "18. Zip Code",
      permanentCountry: "18. Country",
      emergencyName: "19. Emergency Contact Name",
      emergencyAddress: "19. Emergency Address",
      emergencyApt: "19. Apartment/Unit",
      emergencyCity: "19. City",
      emergencyState: "19. State",
      emergencyZip: "19. Zip Code",
      emergencyCountry: "19. Country",
      emergencyEmail: "19. Email",
      emergencyPhone: "19. Phone Number",
      emergencyRelationship: "19. Relationship to Applicant",
      departureDate: "20. Departure Date",
      returnDate: "20. Return Date",
      countriesVisited: "20. Countries To Be Visited",
    },
  },
  "schengen": {
    title: "Schengen Visa Application",
    labels: {
      surname: "1. Surname (Family name)",
      surnameAtBirth: "2. Surname at birth",
      firstNames: "3. First name(s)",
      dateOfBirth: "4. Date of birth",
      placeOfBirth: "5. Place of birth",
      countryOfBirth: "6. Country of birth",
      currentNationality: "7. Current nationality",
      nationalityAtBirth: "7. Nationality at birth",
      otherNationalities: "7. Other nationalities",
      sex: "8. Sex",
      civilStatus: "9. Civil status",
      parentalAuthority: "10. Parental authority / legal guardian",
      nationalIdentityNumber: "11. National identity number",
      travelDocumentType: "12. Type of travel document",
      travelDocumentNumber: "13. Number of travel document",
      dateOfIssue: "14. Date of issue",
      validUntil: "15. Valid until",
      issuedBy: "16. Issued by (country)",
      homeAddress: "19. Home address and email",
      telephone: "19. Telephone no.",
      residencePermit: "20. Residence permit",
      currentOccupation: "21. Current occupation",
      employer: "22. Employer / educational establishment",
      purposeOfJourney: "23. Purpose(s) of the journey",
      additionalInfoPurpose: "24. Additional information on purpose of stay",
      mainDestination: "25. Member State of main destination",
      firstEntryState: "26. Member State of first entry",
      numberOfEntries: "27. Number of entries requested",
      intendedArrivalDate: "Intended date of arrival",
      intendedDepartureDate: "Intended date of departure",
      fingerprintsCollected: "28. Fingerprints collected previously",
      fingerprintsDate: "28. Date fingerprints collected",
      fingerprintsNumber: "28. Visa number (if known)",
      entryPermitIssuedBy: "29. Entry permit issued by",
      entryPermitValidFrom: "29. Entry permit valid from",
      entryPermitValidUntil: "29. Entry permit valid until",
      invitingPersonName: "30. Inviting person(s) / accommodation",
      invitingAddress: "30. Address/email of inviting person",
      invitingTelephone: "30. Telephone No",
      invitingCompanyName: "31. Inviting company/organisation",
      invitingCompanyAddress: "31. Address of inviting company",
      invitingCompanyTelephone: "31. Telephone No of company",
      costCoveredBy: "32. Cost covered by (applicant)",
      costCoveredOther: "32. Cost covered by (other)",
      fillerName: "33. Person filling the form (name)",
      fillerAddress: "33. Address/email of person filling",
      fillerTelephone: "33. Telephone No",
      placeAndDate: "Place and date",
    },
  },
};

export function getFieldLabel(formId: string | undefined, fieldName: string): string {
  if (!formId) return fieldName;
  return fieldLabels[formId]?.labels[fieldName] ?? fieldName;
}
